### ISSUE TITLE
Uncaught ReferenceError: prettyPrint is not defined (in header.php)

### ISSUE THREAD

**Issue by Interned** [rachelbaker/bootstrapwp-Twitter-Bootstrap-for-WordPress#11]
I don't know if it's blocking for the good running of the theme but it was shown by the console as an error. <body <?php body_class(); ?>  onload="prettyPrint()">

**Comment by rahulchrty** [comment]
Same error for me as well "Uncaught ReferenceError: prettyPrint is not defined" while calling prettyPrint ()
